esphome:
  name: sleepy-sensor
  friendly_name: Sleepy Sensor

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:

api:
  encryption:
    key: "" # 修改成自己的 API KEY

ota:
  - platform: esphome
    password: "" # 修改成自己的 OTA 密码

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "Sleepy-Sensor Fallback Hotspot"
    password: "" # 设定自己的备份热点密码

i2c:
  sda: 21
  scl: 22

sensor:
  - platform: aht10
    temperature:
      name: "AHT20 Temperature"
      accuracy_decimals: 1
    humidity:
      name: "AHT20 Humidity"
      accuracy_decimals: 1
    update_interval: 10s

  - platform: bmp280_i2c
    pressure:
      name: "BMP280 Pressure"
      accuracy_decimals: 1
    update_interval: 10s

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO27
      mode: INPUT_PULLUP
      inverted: true
    name: "Light Sensor State"
    filters:
      - delayed_on_off: 3s